# Site settings
title: 'Tiba.art.br'
email: 'contato@tiba.art.br'
description: > # this means to ignore newlines until "baseurl:"
  Atêlier de Cerâmica Artística Tiba. Americana, São Paulo. Aulas de cerâmica 
  e desenho, tingimento e estamparia artesanal, e projetos personalizados.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tiba.art.br" # the base hostname & protocol for your site

twitter_username:
github_username:
facebook_url: "https://www.facebook.com/Atelier-de-Cer%C3%A2mica-Tiba-129901457093967/"

google_api_key: AIzaSyCrk_9bqHdbCeECykIN0kU4HK1AfSfxWs0
address:
  - line: Rua Brigadeiro Faria Lima, 460
  - line: Americana, São Paulo, SP

# Build settings
markdown: kramdown
